# Generated by Django 3.0.7 on 2026-01-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
    ]
